### ISSUE TITLE
Random crashes while playing music using yt-search

### ISSUE THREAD

**Issue by maciejopalinski** [maciejopalinski/MieciekBot#2]
```
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at doDownload (/app/node_modules/miniget/dist/index.js:90:28)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by maciejopalinski** [comment]
Maybe change the search package...

**Comment by maciejopalinski** [comment]
I think it is fixed
