### ISSUE TITLE
YouTube Data API v3 Error: Status code: 429

### ISSUE THREAD

**Issue by maciejopalinski** [maciejopalinski/MieciekBot#4]
This error occurs randomly after some time. Error goes away after restarting a worker and returns after some time.

```
[ERROR] (node:23) UnhandledPromiseRejectionWarning: Error: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:141:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by LeManock** [comment]
OMG same problem

**Comment by maciejopalinski** [comment]
Last verified case was about 14 days ago. I think it was a small error in YouTube Data API. I assume that error went away. Hope it won't come back.
